version: '2'
services:
  bot:
    build: .
    image: joanfont/census-bot
    links:
      - redis
    environment:
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
    volumes:
      - ".:/code/"
      - "./config.yml:/code/config.yml"

  redis:
    image: library/redis:3.2.0
    expose:
      - 6379

